name: Build UHeadless

on:
  push:
    branches: [ contrib ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Directory.Build.props'
      - '.editorconfig'
      - 'Nikcio.UHeadless.sln'
      - 'nuget.config'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ contrib ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Directory.Build.props'
      - '.editorconfig'
      - 'Nikcio.UHeadless.sln'
      - 'nuget.config'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          7.0.x
          8.0.x

    - uses: actions/cache@v4
      id: cache-nuget-uheadless
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-uheadless

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./

    - name: Unit Tests
      run: dotnet run --verbosity normal
      working-directory: ./src/Nikcio.UHeadless.UnitTests

    - name: Integration Tests
      run: dotnet run --verbosity normal
      working-directory: ./src/Nikcio.UHeadless.IntegrationTests
